openapi: 3.0.0
info:
  version: "1.0.0"
  title: Microsoft Graph Integration
  description: Allows to interaction against the Micrososft graph API to perform delegated actions with the application
paths:
  '/calendars':
    get:
      tags:
        - calendars
      summary: Get user calendars
      description: Return the calendar to which the user has access. These calendars need to be added in my calendars through the office portal. The user must be authenticated using the ADD
      parameters: 
        - name: userToken
          in: header
          description: Identify the current authenticated user
          schema:
            type: string
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/CalendarSchema'
  '/calendars/{calendar-id}':
    post:
      tags:
        - calendars
      summary: Create calendar invitation
      description: Create calendar invitation
      parameters: 
        - name: calendar-id
          in: path
          required: true
          description: Identify the current authenticated user
          schema:
            type: string
            description: Id of office online calendar element
            example: AQMkADg4ATdmYzVhLTQxYzctNDUzNS04NjBlLTdjYjIyATFhZDI2ZQBGAAADNOG_5wQdxUao2Tg14XQBegcAsAY1ki5x0E6JhU_6vrKeAgAAAgEGAAAAsAY1ki5x0E6JhU_6vrKeAgAAAhW-AAAA
      requestBody:
        $ref: '#/components/requestBodies/Event'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/CalendarSchema'
    put:
      tags:
        - calendars
      summary: Update calendar invitation
      description: Update calendar invitation
      parameters: 
        - name: calendar-id
          in: path
          required: true
          description: Identify the current authenticated user
          schema:
            type: string
            description: Id of office online calendar element
            example: AQMkADg4ATdmYzVhLTQxYzctNDUzNS04NjBlLTdjYjIyATFhZDI2ZQBGAAADNOG_5wQdxUao2Tg14XQBegcAsAY1ki5x0E6JhU_6vrKeAgAAAgEGAAAAsAY1ki5x0E6JhU_6vrKeAgAAAhW-AAAA
      requestBody:
        $ref: '#/components/requestBodies/Event'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/CalendarSchema'
components:
  requestBodies:
    Event:
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/EventSchema'
      description: The user to create.
      required: true
  schemas:
    EventSchema:
      type: object
      properties:
        attendees: 
          type: array
          items: 
            $ref: "#/components/schemas/AttendeeSchema"
        body: 
            type: object
            items: 
              $ref: "#/components/schemas/BodySchema"
        bodyPreview: 
            type: string
        categories: 
            type: string
        changeKey: 
            type: string
        createdDateTime:
            type: string
        end: 
            type: array
            items: 
              $ref: "#/components/schemas/EventSchema"
        hasAttachments: 
            type: boolean
        iCalUId: 
            type: string
        id:
            type: string
        importance: 
          type: string
        isAllDay:
          type: boolean
        isCancelled: 
          type: boolean
        isOnlineMeeting: 
          type: boolean
        isOrganizer: 
          type: boolean
        isReminderOn: 
          type: boolean
        lastModifiedDateTime: 
          type: string
        location: 
            type: object
            items: 
              $ref: "#/components/schemas/LocationSchema"
        locations: 
            type: array
            items: 
              $ref: "#/components/schemas/LocationSchema"
        onlineMeeting: 
            type: object
            items: 
              $ref: "#/components/schemas/OnlineMeetingInfoSchema"
        onlineMeetingProvider: 
          type: string
        onlineMeetingUrl: 
          type: string
        organizer: 
            type: object
            items: 
              $ref: "#/components/schemas/RecipientSchema"
        originalEndTimeZone: 
          type: string
        originalStart:
          type: string
        originalStartTimeZone: 
          type: string
        recurrence:
            type: object
            items: 
              $ref: "#/components/schemas/PatternedRecurrenceSchema"
        reminderMinutesBeforeStart: 
            type: integer
        responseRequested: 
          type: boolean
        responseStatus:
            type: object
            items: 
              $ref: "#/components/schemas/ResponseStatusSchema"
        sensitivity: 
          type: string
        seriesMasterId: 
          type: string
        showAs: 
          type: string
        start:
            type: object
            items: 
              $ref: "#/components/schemas/DateTimeTimeZoneSchema"
        subject: 
          type: string
        eventType: 
          type: string
        webLink: 
          type: string
        attachments:
            type: array
            items: 
              $ref: "#/components/schemas/AttachmentSchema"
        calendar: 
            type: object
            items: 
              $ref: "#/components/schemas/CalendarSchema"
        extensions: 
            type: array
            items: 
              $ref: "#/components/schemas/ExtensionSchema"
        instances: 
            type: array
            items: 
              $ref: "#/components/schemas/EventSchema"
    CalendarSchema:
      type: object
      required:
        - name
        - id
      properties:
        id:
          type: string
          description: Id of office online calendar element
          example: AQMkADg4ATdmYzVhLTQxYzctNDUzNS04NjBlLTdjYjIyATFhZDI2ZQBGAAADNOG_5wQdxUao2Tg14XQBegcAsAY1ki5x0E6JhU_6vrKeAgAAAgEGAAAAsAY1ki5x0E6JhU_6vrKeAgAAAhW-AAAA
        name:
          type: string
          description: User friendly name showed to users in the office interface
          example: VPC/VPC
        allowedOnlineMeetingProviders:
          type: array
          items:
            type: string
        canEdit: 
          type: boolean
        canShare: 
          type: boolean
        canViewPrivateItems: 
          type: boolean
        changeKey: 
          type: string
        color: 
          type: string
        defaultOnlineMeetingProvider: 
          type: string
        isDefaultCalendar: 
          type: boolean
        isRemovable: 
          type: boolean
        isTallyingResponses: 
          type: boolean
        owner:
          type: object
          items:
            $ref : '#/components/schemas/EmailAddressSchema'
    AttendeeSchema:
          type: object
          properties:
            status: 
              type: object
              items:
                $ref: '#/components/schemas/ResponseStatusSchema'
            attendeeType:
                type: string
            emailAddress:
              type: object
              items:
                $ref : '#/components/schemas/EmailAddressSchema'
    EmailAddressSchema:
      type: object
      properties:
        address:
          type: string
        name:
          type: string
    BodySchema:
      type: object
      properties:
        content: 
          type: string
        contentType:
          type: string
    LocationSchema:
      type: object
      properties:
        address:
          $ref: '#/components/schemas/PhysicalAddressSchema'
        coordinates:
          $ref: '#/components/schemas/OutlookGeoCoordinates'
        displayName: 
          type: string
        locationEmailAddress: 
          type: string
        locationUri: 
          type: string
        locationType: 
          type: string
        uniqueId: 
          type: string
        uniqueIdType: 
          type: string
    OnlineMeetingInfoSchema:
      type: object
      properties:
        conferenceId: 
          type: string
        joinUrl: 
          type: string
        phones:
          type: array
          items:
            $ref: '#/components/schemas/PhoneSchema'
        quickDial: 
          type: string
        tollFreeNumbers:
          type: string
        tollNumber: 
          type: string
    RecipientSchema:
          type: object
    PatternedRecurrenceSchema:
          type: object
    OutlookGeoCoordinates:
      type: object
      properties:
        accuracy: 
          type: integer
        altitude: 
          type: integer
        altitudeAccuracy: 
          type: integer
        latitude: 
          type: integer
        longitude: 
          type: integer
    PhoneSchema:
      type: object
      properties:
        number:
          type: string
        PhoneType:
          type: string
    PhysicalAddressSchema:
      type: object
      properties:
        city: 
          type: string
        countryOrRegion:
          type: string
        postalCode: 
          type: string
        state: 
          type: string
        street: 
          type: string
    ResponseStatusSchema:
      type: object
      properties:
        response:
          type: string
        time:
          type: string
    DateTimeTimeZoneSchema:
      type: object
      properties:
        dateTime:
          type: string
        timeZone:
          type: string
    AttachmentSchema:
      type: object
      properties:
        contentType:
          type: string
        id:
          type: string
        isInline:
          type: boolean
        lastModifiedDateTime:
          type: string
        name: 
          type: string
        size:
          type: integer
    ExtensionSchema:
      type: object
      properties:
        id:
          type: string
# Added by API Auto Mocking Plugin
servers:
  - description: SwaggerHub API Auto Mocking
    url: https://virtserver.swaggerhub.com/Kavoku/MSGraph/1.0.0
